In [6]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('ecommerce.db')

In [7]:
df = pd.read_csv('cleaned_ecommerce_data.csv')
df

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,slaes
0,AG-2011-2040,2011-01-01,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Storage,"Tenex Lockers, Blue",408.0,2,0.0,106.1400,35.46,Medium,2011,408.0
1,IN-2011-47883,2011-01-01,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Supplies,"Acme Trimmer, High Speed",120.0,3,0.1,36.0360,9.72,Medium,2011,120.0
2,HU-2011-1220,2011-01-01,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Storage,"Tenex Box, Single Width",66.0,4,0.0,29.6400,8.17,High,2011,66.0
3,IT-2011-3647632,2011-01-01,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Paper,"Enermax Note Cards, Premium",45.0,3,0.5,-26.0550,4.82,High,2011,45.0
4,IN-2011-47883,2011-01-01,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furnishings,"Eldon Light Bulb, Duo Pack",114.0,5,0.1,37.7700,4.70,Medium,2011,114.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51252,CA-2014-115427,2014-12-31,4/1/2015,Standard Class,Erica Bern,Corporate,California,United States,US,West,...,Binders,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",14.0,2,0.2,4.5188,0.89,Medium,2014,14.0
51253,MO-2014-2560,2014-12-31,5/1/2015,Standard Class,Liz Preis,Consumer,Souss-Massa-Draâ,Morocco,Africa,Africa,...,Binders,"Wilson Jones Hole Reinforcements, Clear",4.0,1,0.0,0.4200,0.49,Medium,2014,4.0
51254,MX-2014-110527,2014-12-31,2/1/2015,Second Class,Charlotte Melton,Consumer,Managua,Nicaragua,LATAM,Central,...,Labels,"Hon Color Coded Labels, 5000 Label Set",26.0,3,0.0,12.3600,0.35,Medium,2014,26.0
51255,MX-2014-114783,2014-12-31,6/1/2015,Standard Class,Tamara Dahlen,Consumer,Chihuahua,Mexico,LATAM,North,...,Labels,"Hon Legal Exhibit Labels, Alphabetical",7.0,1,0.0,0.5600,0.20,Medium,2014,7.0
51256,CA-2014-156720,2014-12-31,4/1/2015,Standard Class,Jill Matthias,Consumer,Colorado,United States,US,West,...,Fasteners,Bagged Rubber Bands,3.0,3,0.2,-0.6048,0.17,Medium,2014,3.0

In [8]:
df.to_sql('cleaned_ecommerce_data', conn, if_exists='replace', index=False)

51257

In [10]:
pd.read_sql_query("SELECT * FROM cleaned_ecommerce_data LIMIT 5", conn)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,slaes
0,AG-2011-2040,2011-01-01,6/1/2011,Standard Class,Toby Braunhardt,Consumer,Constantine,Algeria,Africa,Africa,...,Storage,"Tenex Lockers, Blue",408.0,2,0.0,106.140,35.46,Medium,2011,408.0
1,IN-2011-47883,2011-01-01,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Supplies,"Acme Trimmer, High Speed",120.0,3,0.1,36.036,9.72,Medium,2011,120.0
2,HU-2011-1220,2011-01-01,5/1/2011,Second Class,Annie Thurman,Consumer,Budapest,Hungary,EMEA,EMEA,...,Storage,"Tenex Box, Single Width",66.0,4,0.0,29.640,8.17,High,2011,66.0
3,IT-2011-3647632,2011-01-01,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Paper,"Enermax Note Cards, Premium",45.0,3,0.5,-26.055,4.82,High,2011,45.0
4,IN-2011-47883,2011-01-01,8/1/2011,Standard Class,Joseph Holt,Consumer,New South Wales,Australia,APAC,Oceania,...,Furnishings,"Eldon Light Bulb, Duo Pack",114.0,5,0.1,37.770,4.70,Medium,2011,114.0

In [13]:
# TOP 10 PROFOTABLE PRODUCTS
query = """
SELECT product_name, SUM(profit) AS total_profit
FROM cleaned_ecommerce_data
GROUP BY product_name
ORDER BY total_profit DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

                                        product_name  total_profit
0              Canon imageCLASS 2200 Advanced Copier    25199.9280
1                       Cisco Smart Phone, Full Size    17238.5206
2                    Motorola Smart Phone, Full Size    17027.1130
3                                  Hoover Stove, Red    11807.9690
4               Sauder Classic Bookcase, Traditional    10672.0730
5  Harbour Creations Executive Leather Armchair, ...    10427.3260
6                       Nokia Smart Phone, Full Size     9938.1955
7                  Cisco Smart Phone, with Caller ID     9786.6408
8                  Nokia Smart Phone, with Caller ID     9465.3257
9                                 Belkin Router, USB     8955.0180

In [17]:
# TOP 10 CUSTOMERS BY SALES
query = """
SELECT customer_name, SUM(sales) AS total_sales
FROM cleaned_ecommerce_data
GROUP BY customer_name
ORDER BY total_sales DESC
LIMIT 10;
"""

pd.read_sql_query(query, conn)

      customer_name  total_sales
0      Eric Murdock      19489.0
1        John Grady      19483.0
2     Maria Etezadi      18237.0
3  Theone Pippenger      17416.0
4   Dan Reichenbach      16705.0
5        Ben Ferrer      16661.0
6     Randy Bradley      16399.0
7      Mathew Reese      16125.0
8       Steven Ward      15984.0
9     Paul Gonzalez      15922.0

In [19]:
# REGION WISE TOTAL SALES
query = """
SELECT region, SUM(sales) AS total_sales
FROM cleaned_ecommerce_data
GROUP BY region
ORDER BY total_sales DESC;
"""

pd.read_sql_query(query, conn)

            region  total_sales
0          Central    1805633.0
1            South    1030725.0
2            North     790475.0
3          Oceania     624978.0
4             EMEA     575301.0
5           Africa     537600.0
6   Southeast Asia     531048.0
7       North Asia     453686.0
8             West     422970.0
9     Central Asia     389506.0
10            East     366206.0
11       Caribbean     250701.0
12          Canada      49714.0

In [20]:
# CATEGORY WISE AVERAGE PROFIT
query = """
SELECT category, AVG(profit) AS average_profit
FROM cleaned_ecommerce_data
GROUP BY category;
"""

pd.read_sql_query(query, conn)

          category  average_profit
0        Furniture       29.004043
1  Office Supplies       16.576218
2       Technology       65.455996

In [21]:
# HIGHEST DISCOUNT CATEGORY
query = """
SELECT category, AVG(discount) AS average_discount
FROM cleaned_ecommerce_data
GROUP BY category
ORDER BY average_discount DESC
LIMIT 1;
"""

pd.read_sql_query(query, conn)

    category  average_discount
0  Furniture          0.168034

In [23]:
# OREDRS WITH NEGATIVE PROFIT
query = """
SELECT *
FROM cleaned_ecommerce_data
WHERE profit < 0;
"""

pd.read_sql_query(query, conn)

,order_id,order_date,ship_date,ship_mode,customer_name,segment,state,country,market,region,...,sub_category,product_name,sales,quantity,discount,profit,shipping_cost,order_priority,year,slaes
0,IT-2011-3647632,2011-01-01,5/1/2011,Second Class,Eugene Moren,Home Office,Stockholm,Sweden,EU,North,...,Paper,"Enermax Note Cards, Premium",45.0,3,0.50,-26.0550,4.82,High,2011,45.0
1,ID-2011-80230,2011-01-03,9/1/2011,Standard Class,Ken Lonsdale,Consumer,Auckland,New Zealand,APAC,Oceania,...,Copiers,"Hewlett Wireless Fax, Laser",912.0,4,0.40,-319.4640,107.10,Low,2011,912.0
2,IN-2011-65159,2011-01-03,7/1/2011,Second Class,Larry Blacks,Consumer,National Capital,Philippines,APAC,Southeast Asia,...,Storage,"Tenex Lockers, Industrial",338.0,3,0.45,-122.8005,33.75,High,2011,338.0
3,IN-2011-65159,2011-01-03,7/1/2011,Second Class,Larry Blacks,Consumer,National Capital,Philippines,APAC,Southeast Asia,...,Tables,"Chromcraft Round Table, Adjustable Height",211.0,1,0.55,-70.3995,21.32,High,2011,211.0
4,ID-2011-80230,2011-01-03,9/1/2011,Standard Class,Ken Lonsdale,Consumer,Auckland,New Zealand,APAC,Oceania,...,Chairs,"Hon Rocking Chair, Set of Two",159.0,2,0.40,-95.6760,10.07,Low,2011,159.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12533,IT-2014-3715679,2014-12-31,5/1/2015,Second Class,Jim Kriz,Home Office,North Brabant,Netherlands,EU,Central,...,Art,"BIC Pencil Sharpener, Fluorescent",30.0,2,0.50,-9.6900,4.46,High,2014,30.0
12534,IT-2014-3715679,2014-12-31,5/1/2015,Second Class,Jim Kriz,Home Office,North Brabant,Netherlands,EU,Central,...,Binders,"Avery Binder Covers, Recycled",23.0,4,0.50,-6.4200,3.46,High,2014,23.0
12535,TU-2014-5170,2014-12-31,4/1/2015,Second Class,Valerie Dominguez,Consumer,Konya,Turkey,EMEA,EMEA,...,Accessories,"SanDisk Keyboard, Bluetooth",33.0,1,0.60,-25.2780,3.40,Medium,2014,33.0
12536,ID-2014-54442,2014-12-31,4/1/2015,Standard Class,Muhammed Yedwab,Corporate,National Capital,Philippines,APAC,Southeast Asia,...,Accessories,"Memorex Mouse, Bluetooth",62.0,4,0.45,-37.2660,3.18,Medium,2014,62.0
12537,CA-2014-156720,2014-12-31,4/1/2015,Standard Class,Jill Matthias,Consumer,Colorado,United States,US,West,...,Fasteners,Bagged Rubber Bands,3.0,3,0.20,-0.6048,0.17,Medium,2014,3.0

In [25]:
# MONTHLY SALES TREND
query = """
SELECT
    strftime('%Y', order_date) AS year,
    strftime('%m', order_date) AS month,
    SUM(sales) AS total_sales
FROM cleaned_ecommerce_data
GROUP BY year, month
ORDER BY year, month;
"""

pd.read_sql_query(query, conn)

    year month  total_sales
0   2011    01      63837.0
1   2011    02      60597.0
2   2011    03      77708.0
3   2011    04      80606.0
4   2011    05      90889.0
5   2011    06     142526.0
6   2011    07      75412.0
7   2011    08     132065.0
8   2011    09     153992.0
9   2011    10     122853.0
10  2011    11     175221.0
11  2011    12     199654.0
12  2012    01      81584.0
13  2012    02      64671.0
14  2012    03     100896.0
15  2012    04     102668.0
16  2012    05     133087.0
17  2012    06     173758.0
18  2012    07      98307.0
19  2012    08     167188.0
20  2012    09     180579.0
21  2012    10     155952.0
22  2012    11     225179.0
23  2012    12     197616.0
24  2013    01     100506.0
25  2013    02      94149.0
26  2013    03     125709.0
27  2013    04     118212.0
28  2013    05     152534.0
29  2013    06     232624.0
30  2013    07     155678.0
31  2013    08     209172.0
32  2013    09     253211.0
33  2013    10     169227.0
34  2013    11     239563.0
35  2013    12     256188.0
36  2014    01     139080.0
37  2014    02     120322.0
38  2014    03     160097.0
39  2014    04     154016.0
40  2014    05     185021.0
41  2014    06     258276.0
42  2014    07     158948.0
43  2014    08     276557.0
44  2014    09     302828.0
45  2014    10     257664.0
46  2014    11     348457.0
47  2014    12     303659.0

In [27]:
# MARKE-WISE REVENUE ANALYSIS
query = """
SELECT market, SUM(sales) AS revenue
FROM cleaned_ecommerce_data
GROUP BY market
ORDER BY revenue DESC;
"""

pd.read_sql_query(query, conn)

   market    revenue
0    APAC  1999218.0
1      EU  1801827.0
2   LATAM  1562315.0
3      US  1302568.0
4    EMEA   575301.0
5  Africa   537600.0
6  Canada    49714.0

In [28]:
# TOP PERFORMING SUB CATEGORIES
query = """
SELECT sub_category, SUM(sales) AS total_sales
FROM cleaned_ecommerce_data
GROUP BY sub_category
ORDER BY total_sales DESC;
"""

pd.read_sql_query(query, conn)

   sub_category  total_sales
0        Chairs     926639.0
1       Storage     912660.0
2        Phones     870159.0
3     Bookcases     811505.0
4       Copiers     781641.0
5   Accessories     569592.0
6      Machines     413995.0
7    Appliances     377590.0
8   Furnishings     377018.0
9           Art     370855.0
10      Binders     345346.0
11       Tables     289686.0
12        Paper     244281.0
13     Supplies     210064.0
14    Envelopes     170875.0
15    Fasteners      83240.0
16       Labels      73397.0

In [29]:
# SHIP MODE USAGE ANALYSIS
query = """
SELECT ship_mode, COUNT(*) AS usage_count
FROM cleaned_ecommerce_data
GROUP BY ship_mode
ORDER BY usage_count DESC;
"""

pd.read_sql_query(query, conn)

        ship_mode  usage_count
0  Standard Class        30756
1    Second Class        10301
2     First Class         7503
3        Same Day         2697